name: Test
on: [deployment, deployment_status]

jobs:
  test:
    name: Test API Gateway
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo github obj
        run: echo ${{ github.event.deployment }}